### ISSUE TITLE
Flytta readme.md-filen direkt under root:en på projektet

### ISSUE THREAD

**Issue by fblomstedt41** [BigLudo/Chat_Test#17]
Vi vill att då man kommer in i repot så ska man direkt se dokumentationen.

Så flytta filen direkt under översta nivån, dvs. där pom.xml ligger.
Radera katalogen som heter ReadMe.

**Comment by fblomstedt41** [comment]
@BigLudo städa upp denna lite snabbt så får vi bort den.

**Comment by BigLudo** [comment]
Skickat kort pr
