### ISSUE TITLE
Extend ServerHandler

### ISSUE THREAD

**Issue by fblomstedt41** [BigLudo/Chat_Test#6]
Okej, nu tar vi nästa steg.

1. Vi bygger ut ServerHandler så den implementerar Runnable och kör en "tråd" för att kunna hantera flera klienter.
2. Vi bygger ut ServerHandler så att den hanterar en ArrayList med ClientHandler:s.

Kan skapa en branch som heter feature-extend-server

**Comment by fblomstedt41** [comment]
Bara skriv massa frågor här... kan skapa kod och direkt lägga upp en pull request om du vill också, så kan du köra commit och push om du vill jag ska kolla på det. Så kan jag kommentera.

**Comment by BigLudo** [comment]
Blir bra! Kan jag testa att bygga ut serverhandler då och pusha till den nya branchen så får du säga om det ser bra ut/ vad jag ska ändra?

**Comment by fblomstedt41** [comment]
Du borde kunna testköra nu.
